### ISSUE TITLE
Local FDSN with ISPAQ

### ISSUE THREAD

**Issue by NounoDZ16** [EarthScope/ispaq#22]
I want to use ISPAQ with my own local FDSN server, is it possible to do this without modifying the code?

`./run_ispaq.py -M sample_mean -S DZ.ABZH.*.HHZ  --starttime 2023-08-14 --endtime 2023-08-15 --dataselect_url http://localhost:8081`

`2023-08-22 20:27:14 - INFO - Running ISPAQ version 3.1.1 on Tue Aug 22 20:27:14 2023`
`2023-08-22 20:27:16 - WARNING - Station_url should be the same as dataselect_url when retreiving data from FDSN webservices. Station_url 'IRIS' does not match dataselect_url 'http://localhost:8081'`
`2023-08-22 20:27:17 - INFO - No stations found for DZ.ABZH.*.HHZ`
`2023-08-22 20:27:17 - INFO - No available waveforms for 2023-08-14 matching ['DZ.ABZH.*.HHZ']`
`2023-08-22 20:27:17 - WARNING - "simple" metric calculation generated zero metrics`
`2023-08-22 20:27:17 - INFO - No simple metrics were calculated`
`2023-08-22 20:27:17 - INFO - ALL FINISHED!
`

**Comment by gillian-iris** [comment]
Hi Noureddine DJEMA,

Both the dataselect_url and station_url parameters need to point to the same FDSN server. Can you try: 
`./run_ispaq.py -M sample_mean -S DZ.ABZH.*.HHZ  --starttime 2023-08-14 --endtime 2023-08-15 --dataselect_url http://localhost:8081 --station_url http://localhost:8081`
and let me know if that works?

**Comment by NounoDZ16** [comment]
Hello,
Thank you for your reply, in fact my problem was in the FDSN server which does not contain the response files with the FDSN format, there is only format sc3ml seiscomp format.

I had to use --resp_dir and give the path to the directory of the response files generated by rdseed, it works but it's not the right way I have to try to centralize all the files with FDSN. 

another question concerning the PSD, how can i limit the period axis to 1s when generating the pdf which contains the PNG of the PSD, i have short periode stations which don't need to go up to 100, the graph when it exceeds 2 it drifts.


Noureddine

**Comment by gillian-iris** [comment]
Hi Noureddine,

The x-axis limits of the PDF plots produced directly by ISPAQ are not customizable and they plot the entire range of the PSD values calculated. However, if you go to the EXAMPLES directory, we have a Jupyter Notebook example of ways to further customize PDF plotting in Python using matplotlib and the PSD values stored in the SQlite database:  Example3_plotPDFs.ipynb (also Example2_plotPSDs.ipynb for PSD plots). Instead of `plt.xlim(xmax,xmin)`, you can input your preferred upper and lower limits for xmax and xmin. 

Best,
Gillian

**Comment by NounoDZ16** [comment]
Dear Gillian,
Thank you for your reply, in the example files there is a PDF for a station and Calculate PDFs from PSDs.

in the case Plot PDF for a station, we will save all PSD and PDF values in the database.
`./run_ispaq.py -M psd_corrected -S ANMO --starttime 2020-10-01 --endtime 2020-10-16 --output db --db_name ispaq_example.db`
`./run_ispaq.py -M pdf -S ANMO --starttime 2020-10-01 --endtime 2020-10-16 --output db --db_name ispaq_example.db --pdf_interval aggregated
`

in the Calculate PDFs from PSDs case, I've learned that it's easier to calculate PDFs and plot PNGs, but I haven't found the command that can create PDFs without writing to the database. 

Best regards
Noureddine

**Comment by NounoDZ16** [comment]
Hi,

I've solved my problem, I have 70 stations to save the PSDs in the database, I need more than 1.2 GB for 1 month, is this normal?

Best regards
Noureddine

**Comment by gillian-iris** [comment]
Hi Noureddine,

PSDs do take a lot of storage space. 70 stations, 3 channels each, and 30 days would be on the order of 1 GB in an SQLite database. 

Best regards,
Gillian

**Comment by NounoDZ16** [comment]
Dear Gillian,

Thank you for your reply, I have one last question about noise-spectrogram, from what I've read, from PDF's I can generate the spectrogram, can I do that with ISPAQ?


Noureddine

**Comment by gillian-iris** [comment]
Dear Noureddine,

We have not implemented PDF-mode spectrograms into ISPAQ, but it is a good
suggestion and we'll consider it for a future release.

Best,
Gillian

**Comment by NounoDZ16** [comment]
Dear Gillian,

Thank you very much, it's really very interesting for me to work on ISPAQ metrics, I'm creating a web service that will generate automatic daily and monthly reports, also for web and mobile applications.

Cheers
Noureddine

**Comment by gillian-iris** [comment]
I'm glad that you're finding ISPAQ useful and I'd be interested in what
kinds of reports you're developing and how you're using the metrics. It's
great that you're making a web service.

Best,
Gillian

**Comment by NounoDZ16** [comment]
I have a question about the IRIS web page. Please check the url.

[http://service.iris.edu/mustang/noise-pdf-browser/1/gallery?target=IU.ANMO.00.BH?.M&starttime=2011-03-01&endtime=2011-06-02&interval=month](url)

PSD's images will be generated at the time of the request or they are already generated as PNG's ?

**Comment by gillian-iris** [comment]
The .png images are generated at the time of the request, using PDF numbers
that are pre-calculated at intervals of day, week, month, year, 'all' (if
necessary, combined to return the exact time period requested).

cheers,
Gillian

**Comment by NounoDZ16** [comment]
Thank you for your convincing reply, 

I use this command to calculate PSDs and PDFs and save them in a sqlite database.
`./run_ispaq.py -M psd_corrected,pdf -S DZ.ABZH.*.HHZ --starttime 2023-01-01 --endtime 2023-01-02 --dataselect_url http://10.0.0.30:8081 --resp_dir RESP --station_url DZ_fdns.xml --output db --db_name ispaq_example.db --pdf_interval aggregated --pdf_type text`

and without generating the png's, I have specified in --pdf_type text , text only no plot.

How can I generate the png's from a database when I send a request from a web?


Best regards
Noureddine

**Comment by gillian-iris** [comment]
This is beyond the scope of ISPAQ, but the Examples directory has Jupyter
Notebooks (Example3_plotPDFs.ipynb and Example4_calculatePDFs.ipynb) that
might give you some ideas about code that can plot PDFs from the
database values, which can then be incorporated into an API.

cheers,
Gillian

**Comment by NounoDZ16** [comment]
Dear Gillian,
I'm delighted to announce that I've been able to write the code that generates PDF's using ISPAQ when I send a request from the frontend. 

This is an example how i display png of PDF for one station.
eg:
`http://10.0.0.30:3005/generate_plot?start_date=2023-09-01&end_date=2023-09-10&network=DZ&station=ADJF&channel=HHE`

I still have the problem of the execution time, it takes an average of 20-30s, which I think is a bit long, is there a way to speed up the process?

this is my CPU : Intel® Core™ i7-9800X CPU @ 3.80GHz × 16 


Best regards
Noureddine

**Comment by gillian-iris** [comment]
Great, I'm glad you were able to get that working (although the link
doesn't work for me). I don't have any suggestions on how to increase the
speed.

Best,
Gillian
