### ISSUE TITLE
Problem with installation and usage on macOS M1 chip

### ISSUE THREAD

**Issue by YANG-JAEYEOL** [EarthScope/ispaq#23]
I attempted to install and use ispaq on the macOS M1 chip by setting up the environment in Anaconda. After installation, I activated the ispaq environment (conda activate ispaq) and tried running run_ispaq.py. However, I encountered the following error:

"ERROR: please activate your ispaq environment before running: No module named 'rpy2'"

To verify the presence of the 'rpy2' module, I executed 'import rpy2' in IPython, and the module was indeed available. 

It's worth noting that './run_ispaq.py -h' executed successfully.

I would appreciate guidance on resolving this issue.

**Comment by gillian-earthscope** [comment]
Hi Yang-Jaeyeol,

Can you try: `python run_ispaq.py ...` where "..." is the rest of the command that you are running? There has been an issue in the past where running it as `./run_ispaq.py` has failed with that error message for unknown reasons.

If that doesn't work, can you verify that you have run:
`conda activate ispaq`
`CONDA_SUBDIR=osx-64 conda install -c conda-forge --file ispaq-conda-install.txt`
`python run_ispaq.py -I`

and that `echo $CONDA_DEFAULT_ENV` returns the name of the ispaq environment.

Best,
Gillian
